### ISSUE TITLE
[Request]: Get info about the menu

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2359] opened 2023-10-31 13:49 UTC
I don't know if i'm stupid. If so correct me, but there is currently no way of getting the menu version and so.

### Problem

So the problem is that i can't check if the user is using an outdated version of Yim and if so, tell the user to update Yim so they have new features that are required by the script.

### Solution

Add

- `version.get_branch()` ex. master
- `version.get_hash()` ex. 1d58h6h8j46whw46wjhwhE8HE6
- `version.get_date()` timestamp of the date

### Additional context

It would be also very user friendly to have a build / version id to that is just a number and with every build or so counts up.
This would make it very easy. Ex.
```lua
if version.get_build_id() < 123 then
    log.error("This script requires a newer version of YimMenu")
    return
end
```

**Comment by Yimura** [comment] 2023-10-31 13:53
Imo this shouldn't be a thing that scripts need to worry about. Ideally the menu should tell them that the script expects a newer version of YimMenu and as such will not be able to work or work partially.

**Comment by gir489returns** [comment] 2023-10-31 13:54
All the script really should care about is the build number GTA puts in place, as most scripts rely on Global/Local manipulation. But that also hasn't been a very good identifier of script change in the past, I think 3028 did nothing other than add more anti-cheat crap to the game.

**Comment by xiaoxiao921** [comment] 2023-10-31 14:26
There could be breaking changes in the yimmenu api / new api features that require a specific version

**Comment by Yimura** [comment] 2023-10-31 14:44
Yeah sure but this should maybe be defined by the scripts rather than checked by the script if the menu matches.

```lua
SCRIPT_INFO = { API_VERSION = 1, ONLINE_VERSION = 1.67, BUILD_NUMBER = 3028 }
```
When loading the Lua script we check against these values to see if one of these fails to match and thus stop trying to load the script and mark it as outdated.

**Comment by gir489returns** [comment] 2023-10-31 14:47
There are some scripts which just rely on natives, they will not care what version it's run against, so that check has to be optional.

**Comment by pierrelasse** [comment] 2023-10-31 15:12
Yeah but for example when changes where made to the lua functions, then some players don't have yim updated and it would be cool to be able to tell the user that he needs to update yim.

**Comment by Yimura** [comment] 2023-10-31 15:22
Yes but that can also be achieved from within YimMenu, say for example you use YimMenu Lua API implementation version 1. We make a change or add a function to it and bump the version to 2.
Your script will tell us that it's based on version 1 of the YimMenu Lua impl and YimMenu will detect this and tell the user that the script is outdated, similarly the opposite can be done as well where the Lua API version is 1 in YimMenu and your scripts says it's based of off Lua API version 2. Like this YimMenu can tell the user that the script is based on a newer version of the Lua API and that they should update.

The actual implementation in reality of the versions will be more complex than that but that's functionally how it would be implemented in my opinion.

**Comment by pierrelasse** [comment] 2023-10-31 15:29
Seems like a good idea.
Maybe scripts could also give more info to yim for example a formatted name or a version or smth.

**Comment by Yimura** [comment] 2023-10-31 15:31
That's what the metadata.json is used for in the Github repos if you made one on the YimMenu-Lua organization.

https://github.com/YimMenu-Lua/Casino-Pacino

**Comment by 7HA7MA77** [comment] 2023-11-01 11:28
@Yimura pls cancel gir489 permisions, he abusing power. he doing bad things for projects bcs he dont like me personaly
https://github.com/YimMenu/YimMenu/issues/2363

PS: sorry for offtopic, but he closing my every thread, you probably cant see them

**Comment by 7HA7MA77** [comment] 2023-11-01 11:34
https://github.com/Yimura/Portfolio/issues/1

**Comment by TheGreenBandit** [comment] 2023-11-01 15:15
> @Yimura pls cancel gir489 permisions, he abusing power. he doing bad things for projects bcs he dont like me personaly #2363
> 
> PS: sorry for offtopic, but he closing my every thread, you probably cant see them

dont go in other issues to complain and take away from the topic of the issue. grow up and deal with it you fuck, if u want shit added add it yourself and people will consider it

**Comment by xiaoxiao921** [comment] 2024-08-02 14:23
Duplicate of https://github.com/YimMenu/YimMenu/issues/2717

**Closed by xiaoxiao921** 2024-08-02 14:23 UTC
Labels: request
