### ISSUE TITLE
[Bug]: "Exception while trying to call x native" on any blackscreen

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2152] opened 2023-09-19 11:26 UTC
### Describe the bug

When i exit the kosatka without any scripts loaded, errors come in the console

### Steps To Reproduce

Idk if its for everyone but go in kosatka / set spawnpoint there
Exit via ladder in the room where the planning screen is

### Expected Behavior

No error

### Logs and/or screenshots

[WARN/invoker.cpp:56] Exception caught while trying to call 0xB0034A223497FFCB native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB0034A223497FFCB native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB0034A223497FFCB native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB0034A223497FFCB native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x997ABD671D25CA0B native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB0034A223497FFCB native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB118AF58B5F332A1 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x5E9564D8246B909A native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xB0034A223497FFCB native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xD80958FC74E988A6 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0xDC16122C7A20C933 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x767FBC2AC802EF3D native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.
[WARN/invoker.cpp:56] Exception caught while trying to call 0x2C83A9DA6BFFC4F9 native.

### Store

Steam

### Additional context

Error

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment] 2023-09-19 13:40
This was probably introduced with #2140.

**Comment by gir489returns** [comment] 2023-09-19 13:49
@pierrelasse would you mind testing #2156 for me?

**Comment by pierrelasse** [comment] 2023-09-19 14:41
> @pierrelasse would you mind testing #2156 for me?

I also noticed that sometimes native errors came when blackscreen stuff happend. I hope this helps.

So i tested it......
As soon it was done loading errors went brrrrr (errors came until i killed gta with taskmanager).
[cout.zip](https://github.com/YimMenu/YimMenu/files/12662359/cout.zip)

Unrelated: I also get errors when restarting gta and injecting yimmenu. So when i boot up pc start gta and inject no errors but when i restart gta and inject yimmenu sometimes errors come when starting.
[cout.log](https://github.com/YimMenu/YimMenu/files/12662551/cout.log)

**Comment by gir489returns** [comment] 2023-09-19 14:57
I am not giving you my contact information.

**Comment by pierrelasse** [comment] 2023-09-19 15:06
> I am not giving you my contact information.

Uh ok sorry wtf

**Comment by pierrelasse** [comment] 2023-09-19 15:06
> The crash you are getting is related to decloaking whatever the fuck that is. It is not related to what I changed/fixed. I can't help you with that.

This only happens on your build

**Comment by gir489returns** [comment] 2023-09-19 20:44
I pushed more sanity changes to the build, but I couldn't replicate your complaint. I was able to get random native invocations to fail when entering/exiting the Kosatka, but they were resolved with the previous commit. Either way, I consider this fixed as a cannot reproduce.

**Comment by pierrelasse** [comment] 2023-09-20 07:02
> I pushed more sanity changes to the build, but I couldn't replicate your complaint. I was able to get random native invocations to fail when entering/exiting the Kosatka, but they were resolved with the previous commit. Either way, I consider this fixed as a cannot reproduce.

Okay, i will do further investigation and try if i can fix the issue by chaning settings to see how to reproduce.

**Closed** 2023-09-20 14:27 UTC
Labels: bug
