### ISSUE TITLE
Cant join friends races 

### ISSUE THREAD

**Issue by nilesh-cmd** [YimMenu/YimMenu#3054] opened 2024-05-05 14:40 UTC
### Describe the bug

when i trying to join friends races i can join but when he start the race i just got stuck in and left my friends can play that race without any error. please fix this fast or tell me what is the solution for this because i only like to play parkour races with my other friends so this is my request and bug. thank you

### Steps To Reproduce

i dont know what is this im sorry

### Expected Behavior

when playing races

### Logs

[14:12:44.4310953][INFO/main.cpp:156] Settings Loaded and logger initialized.
[14:12:44.4311302][INFO/main.cpp:158] Yim's Menu Initializing
[14:12:44.4311319][INFO/main.cpp:159] Git Info
	Branch:	master
	Hash:	d9576584f5750a69495e60ba002ea2c7cba9ddf4
	Date:	Fri May 3 18:53:59 2024
[14:12:44.4312101][INFO/main.cpp:171] Windows 10 Pro Version 22H2 (OS Build 19045.4170)
[14:12:44.4346986][DEBUG/thread_pool.cpp:22] Resizing thread pool from 0 to 4
[14:12:44.4355672][INFO/main.cpp:179] Thread pool initialized.
[14:12:44.4371837][INFO/pointers.hpp:94] GTA5 pointers cache is up to date, using it.
[14:12:44.4372026][INFO/pointers.cpp:1839] Loading pointers instance from cache
[14:12:44.4372071][INFO/pointers.cpp:1848] Pointers cache: Loading 218 fields from the cache
[14:12:44.4372191][DEBUG/module.cpp:55] Waiting for socialclub.dll...
[14:12:44.4374397][INFO/pointers.hpp:94] Social Club pointers cache is up to date, using it.
[14:12:44.4374438][INFO/pointers.cpp:1839] Loading pointers instance from cache
[14:12:44.4374460][INFO/pointers.cpp:1848] Pointers cache: Loading 5 fields from the cache
[14:12:44.4374664][INFO/main.cpp:182] Pointers initialized.
[14:12:44.4374694][INFO/main.cpp:189] Disabled anticheat gameskeleton.
[14:12:44.4375958][INFO/main.cpp:192] Byte Patch Manager initialized.
[14:12:44.4382251][INFO/main.cpp:195] Renderer initialized.
[14:12:44.4397442][FATAL/exception_handler.cpp:42] EXCEPTION_ACCESS_VIOLATION
Dumping modules:
GTA5.exe Base Address: 0x7FF7A7E90000 Size: 72949760
ntdll.dll Base Address: 0x7FFFF1890000 Size: 1153536
KERNEL32.DLL Base Address: 0x7FFFF0650000 Size: 513536
KERNELBASE.dll Base Address: 0x7FFFEF460000 Size: 1255936
USER32.dll Base Address: 0x7FFFF0B20000 Size: 584704
win32u.dll Base Address: 0x7FFFEF890000 Size: 42496
GDI32.dll Base Address: 0x7FFFF1530000 Size: 57856
gdi32full.dll Base Address: 0x7FFFEEF40000 Size: 672768
msvcp_win.dll Base Address: 0x7FFFEF760000 Size: 344064
ucrtbase.dll Base Address: 0x7FFFEF060000 Size: 735744
PSAPI.DLL Base Address: 0x7FFFF1700000 Size: 2048
WS2_32.dll Base Address: 0x7FFFF0870000 Size: 275456
RPCRT4.dll Base Address: 0x7FFFF1710000 Size: 922624
CRYPT32.dll Base Address: 0x7FFFEF290000 Size: 1094656
WINTRUST.dll Base Address: 0x7FFFEF3F0000 Size: 293888
msvcrt.dll Base Address: 0x7FFFF1490000 Size: 477184
GFSDK_ShadowLib.win64.dll Base Address: 0x7FFFAA2A0000 Size: 96256
VERSION.dll Base Address: 0x7FFFEA020000 Size: 10752
IMM32.dll Base Address: 0x7FFFF1600000 Size: 125440
DSOUND.dll Base Address: 0x7FFFD7E10000 Size: 380928
bcrypt.dll Base Address: 0x7FFFEF160000 Size: 102912
advapi32.dll Base Address: 0x7FFFEFDA0000 Size: 434176
SHLWAPI.dll Base Address: 0x7FFFEFD40000 Size: 182784
bink2w64.dll Base Address: 0x7FFFB2680000 Size: 307712
sechost.dll Base Address: 0x7FFFF1560000 Size: 422400
ole32.dll Base Address: 0x7FFFEFF00000 Size: 833024
SHELL32.dll Base Address: 0x7FFFF0D20000 Size: 5921280
combase.dll Base Address: 0x7FFFEF8C0000 Size: 2324480
OLEAUT32.dll Base Address: 0x7FFFF07A0000 Size: 608768
WINMM.dll Base Address: 0x7FFFDDB30000 Size: 81408
WININET.dll Base Address: 0x7FFFD99C0000 Size: 2019840
MFPlat.DLL Base Address: 0x7FFFDA900000 Size: 1409024
MF.dll Base Address: 0x7FFFDAAF0000 Size: 340992
cfgmgr32.dll Base Address: 0x7FFFEF190000 Size: 219136
msdmo.dll Base Address: 0x7FFFDBB50000 Size: 13312
shcore.dll Base Address: 0x7FFFF05A0000 Size: 476672
PROPSYS.dll Base Address: 0x7FFFEA8A0000 Size: 631296
MFReadWrite.dll Base Address: 0x7FFF98380000 Size: 918016
WTSAPI32.dll Base Address: 0x7FFFEAC10000 Size: 37888
GFSDK_TXAA_AlphaResolve.win64.dll Base Address: 0x7FFFDAC40000 Size: 48128
d3d9.dll Base Address: 0x7FFFE84F0000 Size: 1371648
D3DCOMPILER_43.dll Base Address: 0x7FFFAA030000 Size: 2423296
DINPUT8.dll Base Address: 0x7FFFD6970000 Size: 169472
XINPUT1_4.dll Base Address: 0x7FFFCD2C0000 Size: 30208
IPHLPAPI.DLL Base Address: 0x7FFFEE2F0000 Size: 166400
powrprof.dll Base Address: 0x7FFFEEDA0000 Size: 70656
winmmbase.dll Base Address: 0x7FFFDAAC0000 Size: 95232
d3dx9_43.dll Base Address: 0x7FFFA9C20000 Size: 2280960
OPENGL32.dll Base Address: 0x7FFFBE970000 Size: 909312
dwmapi.dll Base Address: 0x7FFFECC30000 Size: 98816
kernel.appcore.dll Base Address: 0x7FFFECD30000 Size: 16384
windows.storage.dll Base Address: 0x7FFFED010000 Size: 5853184
DEVOBJ.dll Base Address: 0x7FFFEEC00000 Size: 132608
GLU32.dll Base Address: 0x7FFFD98F0000 Size: 122880
Wldp.dll Base Address: 0x7FFFEE8A0000 Size: 96768
MFCORE.DLL Base Address: 0x7FFFD9390000 Size: 3960320
ksuser.dll Base Address: 0x7FFFD90E0000 Size: 6144
CRYPTBASE.DLL Base Address: 0x7FFFEE810000 Size: 10752
UMPDC.dll Base Address: 0x7FFFEED80000 Size: 34816
bcryptPrimitives.dll Base Address: 0x7FFFEF800000 Size: 408576
RTWorkQ.DLL Base Address: 0x7FFFD8D50000 Size: 105472
MSASN1.dll Base Address: 0x7FFFEEA30000 Size: 34816
gameoverlayrenderer64.dll Base Address: 0x7FFFC0470000 Size: 996352
inputhost.dll Base Address: 0x7FFFE4CE0000 Size: 976384
CoreUIComponents.dll Base Address: 0x7FFFEC190000 Size: 1795072
wintypes.dll Base Address: 0x7FFFEB8D0000 Size: 487424
CoreMessaging.dll Base Address: 0x7FFFEC4F0000 Size: 607744
ntmarta.dll Base Address: 0x7FFFEE050000 Size: 140288
dbghelp.dll Base Address: 0x7FFFD4F50000 Size: 1400320
dbgcore.DLL Base Address: 0x7FFFD02E0000 Size: 136704
d3d12.dll Base Address: 0x7FFFD29B0000 Size: 87552
CRYPTSP.dll Base Address: 0x7FFFEE7F0000 Size: 46080
rsaenh.dll Base Address: 0x7FFFEDF30000 Size: 142336
uxtheme.dll Base Address: 0x7FFFEC940000 Size: 382976
clbcatq.dll Base Address: 0x7FFFEFE50000 Size: 437760
imagehlp.dll Base Address: 0x7FFFF0030000 Size: 45056
dxdiagn.dll Base Address: 0x7FFFA9FA0000 Size: 395264
dxgi.dll Base Address: 0x7FFFED7F0000 Size: 614912
d3d11.dll Base Address: 0x7FFFEAC40000 Size: 1853440
WMICLNT.dll Base Address: 0x7FFFEA430000 Size: 31744
wbemprox.dll Base Address: 0x7FFFE73D0000 Size: 27648
wbemcomn.dll Base Address: 0x7FFFE4500000 Size: 328704
wbemsvc.dll Base Address: 0x7FFFDDB60000 Size: 7168
fastprox.dll Base Address: 0x7FFFE2970000 Size: 708608
amsi.dll Base Address: 0x7FFFD06B0000 Size: 62464
USERENV.dll Base Address: 0x7FFFEEDF0000 Size: 108032
profapi.dll Base Address: 0x7FFFEEE70000 Size: 88064
MpOav.dll Base Address: 0x7FFFD0620000 Size: 212992
gpapi.dll Base Address: 0x7FFFED7C0000 Size: 69120
setupapi.dll Base Address: 0x7FFFF0130000 Size: 887808
cryptnet.dll Base Address: 0x7FFFE9FE0000 Size: 135168
WINNSI.DLL Base Address: 0x7FFFE8D50000 Size: 11776
NSI.dll Base Address: 0x7FFFF1840000 Size: 7680
steam_api64.dll Base Address: 0x63ED0000 Size: 110592
steamclient64.dll Base Address: 0x7FFFAB0E0000 Size: 16407552
tier0_s64.dll Base Address: 0x7FFFBEAA0000 Size: 253952
vstdlib_s64.dll Base Address: 0x7FFFCD370000 Size: 284160
MSWSOCK.dll Base Address: 0x7FFFEE600000 Size: 331776
Secur32.dll Base Address: 0x7FFFD2690000 Size: 11264
SSPICLI.DLL Base Address: 0x7FFFEEE20000 Size: 123904
nvapi64.dll Base Address: 0x7FFFE7C50000 Size: 5836288
drvstore.dll Base Address: 0x7FFFE9E90000 Size: 979456
D3D10_1.DLL Base Address: 0x7FFFD27B0000 Size: 130048
d3d10_1core.dll Base Address: 0x7FFFD7D60000 Size: 7680
nvspcap64.dll Base Address: 0x7FFFAED40000 Size: 2022400
MSCTF.dll Base Address: 0x7FFFEFC20000 Size: 864768
textinputframework.dll Base Address: 0x7FFFE4E40000 Size: 722944
WINSTA.dll Base Address: 0x7FFFEED20000 Size: 190976
nvldumdx.dll Base Address: 0x7FFFE43C0000 Size: 841216
nvwgf2umx.dll Base Address: 0x7FFFB2AF0000 Size: 21957120
NvCamera64.dll Base Address: 0x7FFFA7900000 Size: 4093952
WindowsCodecs.dll Base Address: 0x7FFFE86E0000 Size: 1328128
XINPUT9_1_0.dll Base Address: 0x7FFFEC7C0000 Size: 4096
HID.DLL Base Address: 0x7FFFED7B0000 Size: 20480
dxcore.dll Base Address: 0x7FFFE9BB0000 Size: 150016
d3dcompiler_47_64.dll Base Address: 0x7FFFA6B60000 Size: 3922944
OneCoreCommonProxyStub.dll Base Address: 0x7FFFD2F80000 Size: 16384
OneCoreUAPCommonProxyStub.dll Base Address: 0x7FFFE5910000 Size: 98816
dcomp.dll Base Address: 0x7FFFEBB80000 Size: 1408000
DiscordHook64.dll Base Address: 0x7FFFA67D0000 Size: 793600
D3DCompiler_47.dll Base Address: 0x7FFFEAEB0000 Size: 3396608
MMDevApi.dll Base Address: 0x7FFFE2620000 Size: 387072
XAudio2_7.dll Base Address: 0x7FFFA6400000 Size: 485376
AUDIOSES.DLL Base Address: 0x7FFFD5A30000 Size: 1037312
resourcepolicyclient.dll Base Address: 0x7FFFEC9E0000 Size: 31744
Windows.UI.dll Base Address: 0x7FFFE5680000 Size: 731136
WindowManagementAPI.dll Base Address: 0x7FFFE8D60000 Size: 450048
twinapi.appcore.dll Base Address: 0x7FFFE8B40000 Size: 1457664
avrt.dll Base Address: 0x7FFFE9BA0000 Size: 5632
MessageBus.dll Base Address: 0x7FFFD7110000 Size: 5349888
dhcpcsvc.DLL Base Address: 0x7FFFE8A90000 Size: 61440
napinsp.dll Base Address: 0x7FFFCA810000 Size: 50176
pnrpnsp.dll Base Address: 0x7FFFCA7F0000 Size: 66048
NLAapi.dll Base Address: 0x7FFFEA880000 Size: 68608
DNSAPI.dll Base Address: 0x7FFFEE330000 Size: 600576
winrnr.dll Base Address: 0x7FFFCA7D0000 Size: 32768
wshbth.dll Base Address: 0x7FFFCA7B0000 Size: 43008
fwpuclnt.dll Base Address: 0x7FFFDD7D0000 Size: 283648
rasadhlp.dll Base Address: 0x7FFFDD280000 Size: 7168
socialclub.dll Base Address: 0x7FFFADEB0000 Size: 2710528
chrome_elf.dll Base Address: 0x7FFFBF440000 Size: 901120
libcef.dll Base Address: 0x7FFF6C810000 Size: 151009280
COMDLG32.dll Base Address: 0x7FFFF0050000 Size: 684032
COMCTL32.dll Base Address: 0x7FFFD8E90000 Size: 560128
OLEACC.dll Base Address: 0x7FFFDC1E0000 Size: 260608
UIAutomationCore.DLL Base Address: 0x7FFFC42F0000 Size: 2040832
NETAPI32.dll Base Address: 0x7FFFD3DE0000 Size: 47616
WINHTTP.dll Base Address: 0x7FFFE7B40000 Size: 845312
WINSPOOL.DRV Base Address: 0x7FFFDC290000 Size: 389632
DWrite.dll Base Address: 0x7FFFDB3A0000 Size: 1601024
ncrypt.dll Base Address: 0x7FFFEE910000 Size: 102400
USP10.dll Base Address: 0x7FFFEC790000 Size: 512
urlmon.dll Base Address: 0x7FFFDD2D0000 Size: 1281536
dxva2.dll Base Address: 0x7FFFEC760000 Size: 96256
wevtapi.dll Base Address: 0x7FFFE9830000 Size: 296960
CRYPTUI.dll Base Address: 0x7FFFD5140000 Size: 246272
credui.dll Base Address: 0x7FFFEC740000 Size: 55808
ESENT.dll Base Address: 0x7FFFD82F0000 Size: 2585088
srvcli.dll Base Address: 0x7FFFE72F0000 Size: 54272
netutils.dll Base Address: 0x7FFFEE400000 Size: 19456
iertutil.dll Base Address: 0x7FFFE26B0000 Size: 551424
DSROLE.DLL Base Address: 0x7FFFEA800000 Size: 7680
WKSCLI.DLL Base Address: 0x7FFFEE090000 Size: 45568
SAMCLI.DLL Base Address: 0x7FFFE2F40000 Size: 61440
NTASN1.dll Base Address: 0x7FFFEE8D0000 Size: 81408
wdmaud.drv Base Address: 0x7FFFCEAB0000 Size: 193024
msacm32.drv Base Address: 0x7FFFDABB0000 Size: 17920
MSACM32.dll Base Address: 0x7FFFD4E50000 Size: 74240
midimap.dll Base Address: 0x7FFFD7D50000 Size: 13312
TextShaping.dll Base Address: 0x7FFFD28D0000 Size: 304640
FirewallAPI.dll Base Address: 0x7FFFEDAE0000 Size: 329728
fwbase.dll Base Address: 0x7FFFEDA70000 Size: 151552
FWPolicyIOMgr.dll Base Address: 0x7FFFDACB0000 Size: 205824
ondemandconnroutehelper.dll Base Address: 0x7FFFD3330000 Size: 42496
mfsrcsnk.dll Base Address: 0x7FFFA2440000 Size: 1873408
CompPkgSup.DLL Base Address: 0x7FFFDD290000 Size: 152576
Windows.Media.dll Base Address: 0x7FFFC4700000 Size: 5271040
mp3dmod.dll Base Address: 0x7FFFD0050000 Size: 58880
Windows.ApplicationModel.dll Base Address: 0x7FFFD2CB0000 Size: 556544
AppXDeploymentClient.dll Base Address: 0x7FFFEA090000 Size: 658432
dhcpcsvc6.DLL Base Address: 0x7FFFE8AB0000 Size: 23552
SL_9PKSS.dll Base Address: 0x7FFFA1A00000 Size: 8091136
MSVCP140.dll Base Address: 0x7FFFD69F0000 Size: 340480
VCRUNTIME140_1.dll Base Address: 0x7FFFD69C0000 Size: 15360
VCRUNTIME140.dll Base Address: 0x7FFFD7B60000 Size: 73728
MSVCP140_2.dll Base Address: 0x7FFFBF130000 Size: 196096
winbrand.dll Base Address: 0x7FFFCEA30000 Size: 161280
Dumping registers:
RAX: 0x35
RCX: 0x2391A2BF5A8
RDX: 0x15
RBX: 0x2392CCA1E90
RSI: 0x23950023FFF
RDI: 0x2395002D5B0
RSP: 0xC5745EF490
RBP: 0xC5745EF529
R8:  0x7FF7AAD8A920
R9:  0x23950020000
R10: 0x2
R11: 0x2392CC9F6D0
R12: 0x8
R13: 0x23950027CC0
R14: 0x2392CCA1E60
R15: 0x2392C8D9E38
Dumping stacktrace:
[0]	GTA5.exe+0x1623430 0x7FF7A94B3430
[1]	GTA5.exe+0x1623F5B 0x7FF7A94B3F5B
[2]	GTA5.exe+0xA58F60 0x7FF7A88E8F60
[3]	GTA5.exe+0x162463D 0x7FF7A94B463D
[4]	GTA5.exe+0xA4D8FC 0x7FF7A88DD8FC
[5]	GTA5.exe+0xA51148 0x7FF7A88E1148
[6]	GTA5.exe+0x1633449 0x7FF7A94C3449
[7]	GTA5.exe+0x1633449 0x7FF7A94C3449
[8]	GTA5.exe+0x1632C7F 0x7FF7A94C2C7F
[9]	GTA5.exe+0x276A4 0x7FF7A7EB76A4
[10]	GTA5.exe+0x20D8B 0x7FF7A7EB0D8B
[11]	GTA5.exe+0x1632888 0x7FF7A94C2888
[12]	GTA5.exe+0x1494 0x7FF7A7E91494
[13]	GTA5.exe+0x130904F 0x7FF7A919904F
[14]	GTA5.exe+0x1825DCC 0x7FF7A96B5DCC
[15]	KERNEL32.DLL BaseThreadInitThunk
[16]	ntdll.dll RtlUserThreadStart
--------End of exception--------

[14:12:44.4440960][INFO/main.cpp:199] Fiber pool initialized.
[14:12:44.4646355][INFO/main.cpp:202] HTTP Client initialized.
[14:12:46.5597038][DEBUG/thread_pool.cpp:96] Thread 15812 executing font_mgr.cpp:104
[14:12:46.5606731][INFO/main.cpp:205] Translation Service initialized.
[14:12:46.6191980][INFO/main.cpp:208] Hooking initialized.
[14:12:46.6270819][DEBUG/gta_data_service.cpp:160] Loading data from cache.
[14:12:46.6270908][INFO/gta_data_service.cpp:172] Loading 1051 peds from cache.
[14:12:46.6274184][INFO/gta_data_service.cpp:190] Loading 843 vehicles from cache.
[14:12:46.6277027][INFO/gta_data_service.cpp:207] Loading 119 weapons from cache.
[14:12:46.6277063][INFO/gta_data_service.cpp:208] Loading 380 weapon components from cache.
[14:12:46.6277212][DEBUG/gta_data_service.cpp:166] Loaded all data from cache.
[14:12:46.6314568][DEBUG/thread_pool.cpp:96] Thread 15812 executing player_database_service.cpp:285
[14:12:46.6316199][INFO/main.cpp:228] Registered service instances...
[14:12:46.6316359][INFO/main.cpp:231] Finished initialising services.
[14:12:46.6317537][INFO/main.cpp:252] Scripts registered.
[14:12:46.6586262][INFO/main.cpp:255] Hooking enabled.
[14:12:46.6602370][INFO/main.cpp:258] Dynamic native hooker initialized.
[14:12:46.6797577][INFO/lua_module.cpp:330] Loaded samurais_animations.lua
[14:12:46.6798424][INFO/main.cpp:262] Lua manager initialized.
[14:12:46.7250712][INFO/backend.cpp:53] Starting script: Self
[14:12:46.7251142][INFO/backend.cpp:78] Starting script: Weapons
[14:12:46.7251371][INFO/backend.cpp:101] Starting script: Vehicles
[14:12:46.7251576][INFO/backend.cpp:117] Starting script: Miscellaneous
[14:12:46.7251895][INFO/backend.cpp:138] Starting script: Remote
[14:12:46.7251917][INFO/backend.cpp:153] Starting script: Ls customs
[14:12:46.7251960][INFO/backend.cpp:165] Starting script: Rainbow paint
[14:12:46.7251974][INFO/backend.cpp:177] Starting script: Disable Control Action
[14:12:46.7252024][INFO/backend.cpp:190] Starting script: World
[14:12:46.7363304][INFO/tunables_service.cpp:36] Loading tunables from cache
[14:12:49.6602191][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x318D08
[14:12:49.6639657][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x961FBC
[14:12:49.6639959][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0xA66114
[14:12:49.6641638][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x66F09C
[14:12:49.6641701][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x66F0C4
[14:12:49.6641848][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x66F0EC
[14:12:49.6641894][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x66F074
[14:12:49.6657932][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x335660
[14:12:49.6658071][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x335638
[14:12:49.6658255][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x4015B8
[14:12:49.6751666][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x45B164
[14:12:49.6753898][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x45A3A8
[14:12:49.6753982][INFO/queue_dependency.cpp:63] Blocking AC Verifier 0x5CAA60
[14:14:16.6750677][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: MM; DATA: "mmList":"4669726577616C6C4150492E646C6C00|6677626173652E646C6C00|4657506F6C696379494F4D67722E646C6C00|6F6E64656D616E64636F6E6E726F75746568656C7065722E646C6C00|6D66737263736E6B2E646C6C00|436F6D70506B675375702E444C4C00|57696E646F77732E4D656469612E646C6C00|
[14:15:00.2732558][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[14:15:00.2734042][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: AWARD_XP; DATA: "amt":18880991,"type":3136273443,"cat":654913086,"pt":1834276272,"slot":0
[14:17:24.8332952][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[14:17:33.3849622][WARN/reaction.cpp:60] Received Start Script from EvilLexer (207895666)
[14:17:33.5848320][WARN/reaction.cpp:60] Received Start Script from EvilLexer (207895666)
[14:18:39.3594919][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: DIG; DATA: "gamer":"SC 207895666","action":"SCRIPT","data":{"a":2,"b":2},"id":-9104380740461413834
[14:23:42.9119197][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[14:23:42.9120628][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false
[14:24:27.9760385][WARN/reaction.cpp:60] Received Start Script from EvilLexer (207895666)
[14:25:32.2337755][DEBUG/script_function.cpp:35] Found pattern RSD in script PauseMenu_Multiplayer
[14:25:58.3292564][WARN/prepare_metric_for_sending.cpp:93] BAD METRIC: UVC; DATA: "vc":false

### Store

Steam

### Language

English

### YimMenu Language

English (US)

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by nilesh-cmd** [comment] 2024-05-05 14:43
Bythe way i forgot to say i can create races and its fine. the problem is i cant join others

**Comment by rkwapisz** [comment] 2024-05-05 18:35
Probably a duplicate of https://github.com/YimMenu/YimMenu/issues/3042 resolved with https://github.com/YimMenu/YimMenu/pull/3045

**Comment by nilesh-cmd** [comment] 2024-05-06 12:01
rkwapisz how to fix this sorry for my bad English or is there any tutorial or something please reply me or tell me what to do

**Comment by rkwapisz** [comment] 2024-05-06 18:56
> rkwapisz how to fix this sorry for my bad English or is there any tutorial or something please reply me or tell me what to do

You can watch the PR to see when it gets merged into master, then download the nightly build or compile it yourself.

**Comment by rkwapisz** [comment] 2024-05-07 21:39
This can be closed now that https://github.com/YimMenu/YimMenu/pull/3045 was pulled in.

**Closed** 2024-05-08 01:32 UTC
Labels: bug
