### ISSUE TITLE
[Bug]: Bounty not working

### ISSUE THREAD

**Issue by ghost** [YimMenu/YimMenu#1966] opened 2023-08-13 10:12 UTC
### Describe the bug

I don't know if bounty assignment works for anyone or not. I just switched from steam to epic and my bountyscript stopped working. Maybe it's some kind of hotfix from rockstar.

### Steps To Reproduce

1. Call command `/bountyall`
2. Nothing happens

### Expected Behavior

A bounty is assigned to all players

### Logs and/or screenshots

```
<paste your logs here>
```

### Store

Epic Games

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by gir489returns** [comment] 2023-08-13 20:26
This is a duplicate of #1544.

**Closed as completed** 2023-08-13 20:27 UTC
Labels: bug
