### ISSUE TITLE
[Bug]: Crash with much errors

### ISSUE THREAD

**Issue by pierrelasse** [YimMenu/YimMenu#2256] opened 2023-10-11 12:46 UTC
### Describe the bug

When injecting, loaded in story mode, i crashed with many errors.
I don't know if this is only for me or also others.

### Steps To Reproduce

Start gta
Inject dll

### Expected Behavior

Injecting without any errors and freezing and then crashing

### Logs and/or screenshots

[cout.log](https://github.com/YimMenu/YimMenu/files/12869881/cout.log)

### Store

Other (please mention in "Additional context")

### Additional context

d

### Build

- [X] I've confirmed the issue exists on the latest version of YimMenu

### Coload

- [X] I've tested this without co-loading anything.

**Comment by ege-art** [comment] 2023-10-11 13:05
Same happens to me

**Comment by lonelybud** [comment] 2023-10-11 13:09
try latest yim build and also update rockstar social club launcher

**Comment by binded-zz** [comment] 2023-10-11 13:12
seems to work for me lastest build last night fixed self gui 
played for almost two hours before i ended up crashing my self out with to many peds i spawned on some one using SHC menu
just loaded in to story fine as well

**Comment by lonelybud** [comment] 2023-10-11 13:15
> I've confirmed the issue exists on the latest version of YimMenu

did you checked latest build.

**Comment by xiaoxiao921** [comment] 2023-10-11 13:49
Duplicate of https://github.com/YimMenu/YimMenu/issues/2252

**Closed by xiaoxiao921** 2023-10-11 13:49 UTC
Labels: bug
